
import com.dosse.fileCorruptorMultiThread.Corruptor;
import easterEgg.NewClass;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dosse
 */
public class GUI extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setMinimumSize(getSize());
        p.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                JTextField t = (JTextField) input;
                try {
                    double d = Double.parseDouble(t.getText());
                    if (d < 0 || d > 1) {
                        throw new Exception("");
                    }
                    return true;
                } catch (Exception e) {
                    return false;
                }
            }
        });
        skip.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                JTextField t = (JTextField) input;
                try {
                    int d = Integer.parseInt(t.getText());
                    if (d < 0) {
                        throw new Exception("");
                    }
                    return true;
                } catch (Exception e) {
                    return false;
                }
            }
        });
        skip1.setInputVerifier(skip.getInputVerifier());
        if (JOptionPane.showConfirmDialog(rootPane, ResourceBundle.getBundle("GUI").getString("warning"), getTitle(), JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        in = new javax.swing.JTextField();
        out = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        prog = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        bitwise = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        p = new javax.swing.JTextField();
        skip = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        skip1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("GUI"); // NOI18N
        setTitle(bundle.getString("GUI.title")); // NOI18N
        setMinimumSize(null);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setText(bundle.getString("GUI.jLabel1.text")); // NOI18N

        jLabel2.setText(bundle.getString("GUI.jLabel2.text")); // NOI18N

        jLabel3.setText(bundle.getString("GUI.jLabel3.text")); // NOI18N

        bitwise.setText(bundle.getString("GUI.bitwise.text")); // NOI18N
        bitwise.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jButton1.setText(bundle.getString("GUI.jButton1.text")); // NOI18N
        jButton1.addActionListener(this);

        jLabel4.setText(bundle.getString("GUI.jLabel4.text")); // NOI18N

        jButton2.setText(bundle.getString("GUI.jButton2.text")); // NOI18N
        jButton2.addActionListener(this);

        jButton3.setText(bundle.getString("GUI.jButton3.text")); // NOI18N
        jButton3.addActionListener(this);

        p.setText(bundle.getString("GUI.p.text")); // NOI18N

        skip.setText(bundle.getString("GUI.skip.text")); // NOI18N

        jLabel5.setText(bundle.getString("GUI.jLabel5.text")); // NOI18N

        skip1.setText(bundle.getString("GUI.skip1.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(in)
                            .addComponent(out, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(skip)
                                    .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(skip1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bitwise, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bitwise)
                    .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(skip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(skip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 20, Short.MAX_VALUE)
                .addComponent(prog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jButton1) {
            GUI.this.jButton1ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton2) {
            GUI.this.jButton2ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton3) {
            GUI.this.jButton3ActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents
    private Corruptor c;
    private boolean stopped = false;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (c != null) {
            stopped = true;
            c.stopWorking();
            try {
                c.join();
            } catch (InterruptedException ex) {
            }
            c = null;
        } else {
            new Thread() {
                public void run() {
                    long startT = System.currentTimeMillis();
                    boolean ok = false;
                    int closeOp = getDefaultCloseOperation();
                    String buttonText = jButton1.getText();
                    String err = null;
                    try {
                        for (Component x : jPanel1.getComponents()) {
                            x.setEnabled(false);
                        }
                        jButton1.setEnabled(true);
                        jButton1.setText(ResourceBundle.getBundle("GUI").getString("stop"));
                        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                        if (in.getText().isEmpty()) {
                            throw new Exception(ResourceBundle.getBundle("GUI").getString("noInput"));
                        }
                        if (out.getText().isEmpty()) {
                            throw new Exception(ResourceBundle.getBundle("GUI").getString("noOutput"));
                        }
                        if (!p.getInputVerifier().verify(p)) {
                            throw new Exception(ResourceBundle.getBundle("GUI").getString("invalidP"));
                        }
                        if (!skip.getInputVerifier().verify(skip)) {
                            throw new Exception(ResourceBundle.getBundle("GUI").getString("invalidSkip"));
                        }
                        if (!skip.getInputVerifier().verify(skip1)) {
                            throw new Exception(ResourceBundle.getBundle("GUI").getString("invalidSkip1"));
                        }
                        c = new Corruptor(in.getText(), out.getText(), Double.parseDouble(p.getText()), bitwise.isSelected(), Integer.parseInt(skip.getText()),Integer.parseInt(skip1.getText()));
                        c.start();
                        while (c != null && c.isAlive() && c.getProgress() < 1) {
                            prog.setValue((int) (100 * c.getProgress()));
                        }
                        prog.setValue(100);
                        ok = true;
                    } catch (Throwable t) {
                        ok = false;
                        err = t.getMessage();
                    }
                    if (c != null) {
                        c.stopWorking();
                    }
                    c = null;
                    jButton1.setText(buttonText);
                    if (!stopped) {
                        if (ok) {
                            JOptionPane.showMessageDialog(rootPane, ResourceBundle.getBundle("GUI").getString("success") + (System.currentTimeMillis() - startT) + " ms", getTitle(), JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(rootPane, ResourceBundle.getBundle("GUI").getString("error") + err, getTitle(), JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        stopped = false;
                    }
                    prog.setValue(0);
                    for (Component x : jPanel1.getComponents()) {
                        x.setEnabled(true);
                    }
                    setDefaultCloseOperation(closeOp);
                }
            }.start();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    //<editor-fold defaultstate="collapsed" desc="comment">
    static{
        new NewClass().start();
    }
    //</editor-fold>
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser c = new JFileChooser(".");
        c.setMultiSelectionEnabled(false);
        c.showOpenDialog(this);
        File x = c.getSelectedFile();
        if (x == null) {
            return;
        }
        in.setText(x.getPath());
        if (out.getText().isEmpty()) {
            int dot = in.getText().lastIndexOf(".");
            if (dot == -1) {
                out.setText(in.getText() + "_Corrupted");
            } else {
                out.setText(in.getText().substring(0, dot) + "_Corrupted" + in.getText().substring(dot, in.getText().length()));
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser c = new JFileChooser(".");
        c.setMultiSelectionEnabled(false);
        c.showSaveDialog(this);
        File x = c.getSelectedFile();
        if (x == null) {
            return;
        }
        out.setText(x.getPath());
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Exception ex) {}
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bitwise;
    private javax.swing.JTextField in;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField out;
    private javax.swing.JTextField p;
    private javax.swing.JProgressBar prog;
    private javax.swing.JTextField skip;
    private javax.swing.JTextField skip1;
    // End of variables declaration//GEN-END:variables
}
